"""empty message

Revision ID: e75b9983e58b
Revises: ddf514161080
Create Date: 2022-10-26 16:15:59.129326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75b9983e58b'
down_revision = 'ddf514161080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('base_exp', sa.String(), nullable=True))
    op.drop_column('pokemon', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pokemon', 'base_exp')
    # ### end Alembic commands ###
